apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rdbw-prod

secretGenerator:
  - name: db-password
    literals:
      - password=supersecretpasswordhere
  - name: django
    literals:
      - secret=secretkey123
resources:
  # - prod.backend.ingress.yaml
  # - prod.backend.yaml
  # - prod.backend-static.ingress.yaml
  # - prod.backend-static.yaml
  # - prod.frontend.configmap.yaml
  # - prod.frontend.ingress.yaml
  # - prod.frontend.yaml
  - prod.db.yaml
  - prod.db.ingress.yaml